/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Presentacion2.java
 *
 * Created on 06-ene-2018, 9:25:48
 */
package Principal;

import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author back
 */
public class Presentacion2 extends javax.swing.JFrame {
 Timer contador;
  int a;
    /** Creates new form Presentacion2 */
    public Presentacion2() {
       setUndecorated(true);
       initComponents();
         i();
         setLocationRelativeTo(null);
         bloqueo();
       this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
        contador = new Timer(50, new claseTimer());
    contador.start();
    }
     void i(){
    Image icon;
    icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ImaPeq/logo.png"));
    
            
            
    setIconImage(icon);
    setVisible(true);
  }
  void  bloqueo(){
       jLabel2.setVisible(false); 
       
         jLabel4.setVisible(false); 
          jLabel5.setVisible(false); 
           jLabel6.setVisible(false);
            jLabel7.setVisible(false); 
             jLabel8.setVisible(false); 
              jLabel9.setVisible(false); 
              
            
             
           
           
    }
    
public class claseTimer implements ActionListener
  {
   public claseTimer() { 
   }
    
    public void actionPerformed(ActionEvent e)
    {
     
      if(a<=100){
           a+=1;
       if(a<=10){
           jLabel2.setVisible(true);
        jLabel2.setVisible(true);
       File ruta = new File("C:\\Archivos de programa\\Sana\\Menu\\lo4.png");
           String d=(String.valueOf(ruta));
            Image foto= getToolkit().getImage(d);
           jLabel12.setIcon(new ImageIcon(foto)); 
           jLabel13.setText("SANA-Software 2017-2018: Verificando.");
            
      }
        if(a>10&& a<=20){
            jLabel4.setVisible(true);
         
            
                 

          
         } 
         if(a>20&& a<=30){
            jLabel5.setVisible(true);
            File ruta = new File("C:\\Archivos de programa\\Sana\\Menu\\lo3.png");
           String d=(String.valueOf(ruta));
            Image foto= getToolkit().getImage(d);
           jLabel12.setIcon(new ImageIcon(foto));   
           jLabel13.setText("SANA-Software 2017-2018: Verificando..");       

          
         } 
          if(a>30&& a<=40){
            jLabel6.setVisible(true);
         
                 

          
         } 
           if(a>50&& a<=60){
            jLabel7.setVisible(true);
              File ruta = new File("C:\\Archivos de programa\\Sana\\Menu\\lo2.png");
           String d=(String.valueOf(ruta));
            Image foto= getToolkit().getImage(d);
           jLabel12.setIcon(new ImageIcon(foto)); 
              jLabel13.setText("SANA-Software 2017-2018: Datos.");
                 

          
         } 
            if(a>60&& a<=70){
            jLabel8.setVisible(true);
          
          jLabel13.setText("SANA-Software 2017-2018: Datos..");   
                 

          
         } 
             if(a>70&& a<=80){
                 
            jLabel9.setVisible(true);
            
            File ruta = new File("C:\\Archivos de programa\\Sana\\Menu\\letra logo.png");
           String d=(String.valueOf(ruta));
            Image foto= getToolkit().getImage(d);
           jLabel12.setIcon(new ImageIcon(foto)); 
              jLabel13.setText("SANA-Software 2017-2018: Seguridad.");       

          
         } 
              if(a>80&& a<=90){
           jLabel9.setVisible(true);
           jLabel13.setText("SANA-Software 2017-2018: Seguridad..");
            
                 

          
         } 
              
          if(a>90&& a<=100){
           jLabel9.setVisible(true);
           jLabel13.setText("SANA-Software 2017-2018: Listo");
        
   
         dispose();
          
         }
                    

           
      }
      else
      {
       
      Presentacion2.this.contador.stop(); 
         new ModIngUsu().setVisible(true);
    
      
       
      }
            
      
      }
     
      }
  void salir(){
      
  }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(-1,true));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(-20, 30, 320, 210);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/cargar3.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 260, 30, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/cargar3.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 210, 30, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/cargar3.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 170, 30, 110);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/cargar3.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 130, 30, 150);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/cargar3.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 80, 30, 200);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/cargar3.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(380, 30, 30, 250);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/cargar3.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(410, 10, 30, 270);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel13.setForeground(new java.awt.Color(51, 102, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 280, 430, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImaGra/proc_2.gif"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 0, 310, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Presentacion2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
